"""Colour vibrance for any GPU on KDE Plasma (Wayland), like NVIDIA's Digital Vibrance.

NVIDIA's setting is a saturation matrix applied to the display output. KWin (Plasma 6) can colour-
manage each monitor with an ICC profile, and RigDeck uses that: it writes a profile that describes
the monitor as *less* saturated than sRGB by the chosen amount, so KWin drives the panel harder to
compensate — a saturation boost for everything on that screen, greys and white unchanged.

Scale as in NVIDIA's control panel: 50% = normal, 100% = twice the saturation, 0% = greyscale.
Maths: in linear RGB, S(s) = (1-s)·[luma;luma;luma] + s·I. KWin maps content through the
profile's inverse, so a profile with colorants M_sRGB·S⁻¹ yields device = S·content. Colorants are
Bradford-adapted to D50 (ICC v4); tone curve gamma 2.2, which KWin assumes for SDR screens.
"""
from __future__ import annotations

import os
import re
import shutil
import struct
import subprocess

from . import config

DIR = os.path.join(os.environ.get("XDG_DATA_HOME", os.path.expanduser("~/.local/share")), "rigdeck", "vibrance")
NEUTRAL = 50

SRGB = [[0.4124564, 0.3575761, 0.1804375], [0.2126729, 0.7151522, 0.0721750], [0.0193339, 0.1191920, 0.9503041]]
LUMA = [0.2126729, 0.7151522, 0.0721750]          # Y row of SRGB: keeps luminance while saturating
BRADFORD_D65_D50 = [[1.0478112, 0.0228866, -0.0501270], [0.0295424, 0.9904844, -0.0170491],
                    [-0.0092345, 0.0150436, 0.7521316]]
D50 = [0.9642, 1.0, 0.8249]


class VibranceError(RuntimeError):
    pass


# ---- matrices -------------------------------------------------------------------------

def _mul(a, b):
    return [[sum(a[i][k] * b[k][j] for k in range(3)) for j in range(3)] for i in range(3)]


def _inv(m):
    (a, b, c), (d, e, f), (g, h, i) = m
    det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    return [[(e * i - f * h) / det, (c * h - b * i) / det, (b * f - c * e) / det],
            [(f * g - d * i) / det, (a * i - c * g) / det, (c * d - a * f) / det],
            [(d * h - e * g) / det, (b * g - a * h) / det, (a * e - b * d) / det]]


def saturation_matrix(s: float):
    return [[(1 - s) * LUMA[j] + (s if i == j else 0) for j in range(3)] for i in range(3)]


def colorants(level: int):
    """D50 XYZ of the profile's red, green, blue colorants for a vibrance level (columns)."""
    s = max(level, 5) / NEUTRAL                    # 0% would be singular; 5% is nearly grey already
    m = _mul(BRADFORD_D65_D50, _mul(SRGB, _inv(saturation_matrix(s))))
    return [[m[r][c] for r in range(3)] for c in range(3)]


# ---- ICC v4 writer --------------------------------------------------------------------

def _s15(v: float) -> bytes:
    return struct.pack(">i", round(v * 65536))


def _xyz(v) -> bytes:
    return b"XYZ \0\0\0\0" + b"".join(_s15(x) for x in v)


def _mluc(text: str) -> bytes:
    s = text.encode("utf-16-be")
    return b"mluc\0\0\0\0" + struct.pack(">II", 1, 12) + b"enUS" + struct.pack(">II", len(s), 28) + s


def profile(level: int, name: str) -> bytes:
    """An ICC v4 matrix/TRC display profile for this vibrance level."""
    r, g, b = colorants(level)
    curve = b"curv\0\0\0\0" + struct.pack(">IH", 1, round(2.2 * 256)) + b"\0\0"
    tags = [(b"desc", _mluc(name)), (b"cprt", _mluc("Generated by RigDeck (no copyright)")),
            (b"wtpt", _xyz(D50)), (b"chad", b"sf32\0\0\0\0" + b"".join(_s15(x) for row in BRADFORD_D65_D50 for x in row)),
            (b"rXYZ", _xyz(r)), (b"gXYZ", _xyz(g)), (b"bXYZ", _xyz(b)),
            (b"rTRC", curve), (b"gTRC", curve), (b"bTRC", curve)]
    table, data = b"", b""
    offset = 128 + 4 + 12 * len(tags)
    for sig, body in tags:
        table += sig + struct.pack(">II", offset + len(data), len(body))
        data += body + b"\0" * (-len(body) % 4)
    size = offset + len(data)
    header = (struct.pack(">I", size) + b"lcms" + bytes([4, 0x30, 0, 0]) + b"mntrRGB XYZ "
              + struct.pack(">6H", 2026, 1, 1, 0, 0, 0) + b"acsp" + b"\0" * 4 + b"\0" * 4 + b"\0" * 8
              + b"\0" * 8 + struct.pack(">I", 0) + b"".join(_s15(x) for x in D50) + b"rgdk" + b"\0" * 16 + b"\0" * 28)
    assert len(header) == 128
    return header + struct.pack(">I", len(tags)) + table + data


# ---- applying through KWin (kscreen-doctor) ----------------------------------------------

def available() -> bool:
    return shutil.which("kscreen-doctor") is not None and os.environ.get("XDG_SESSION_TYPE") == "wayland"


def _doctor(*args: str) -> str:
    r = subprocess.run(["kscreen-doctor", *args], capture_output=True, text=True, timeout=15)
    if r.returncode != 0:
        raise VibranceError((r.stderr or r.stdout).strip() or "kscreen-doctor failed")
    return r.stdout


def outputs() -> list[dict]:
    """Connected, enabled outputs with their colour settings, from `kscreen-doctor -o`."""
    text = re.sub(r"\x1b\[[0-9;]*m", "", _doctor("-o"))
    out, cur = [], None
    for line in text.splitlines():
        m = re.match(r"Output: \d+ (\S+)", line)
        if m:
            cur = {"name": m.group(1), "enabled": False, "connected": False, "hdr": False, "icc": "", "source": ""}
            out.append(cur)
            continue
        if cur is None:
            continue
        s = line.strip()
        if s in ("enabled", "connected"):
            cur[s] = True
        elif s.startswith("HDR:"):
            cur["hdr"] = s.split(":", 1)[1].strip() == "enabled"
        elif s.startswith("ICC profile:"):
            v = s.split(":", 1)[1].strip()
            cur["icc"] = "" if v == "none" else v
        elif s.startswith("Color profile source:"):
            cur["source"] = s.split(":", 1)[1].strip()
    for o in out:
        o["level"] = level_of(o)
    return [o for o in out if o["connected"] and o["enabled"]]


def level_of(o: dict) -> int:
    """The vibrance level in effect (from RigDeck's profile name), NEUTRAL if none of ours."""
    m = re.search(r"rigdeck-vibrance-\S+-(\d+)\.icc$", o.get("icc") or "")
    return int(m.group(1)) if m and o.get("source") == "ICC" else NEUTRAL


def prune(output: str, keep: str = "") -> None:
    """Delete this output's old profiles; KWin only ever reads the one it was last given (`keep`)."""
    pattern = re.compile(rf"rigdeck-vibrance-{re.escape(output)}-\d+\.icc")
    try:
        names = os.listdir(DIR)
    except FileNotFoundError:
        return
    for n in names:
        path = os.path.join(DIR, n)
        if pattern.fullmatch(n) and path != keep:
            try:
                os.remove(path)
            except OSError:
                pass


def apply(output: str, level: int) -> None:
    """Set an output's vibrance; NEUTRAL restores the colour profile it had before RigDeck."""
    level = max(0, min(100, int(level)))
    current = next((o for o in outputs() if o["name"] == output), None)
    if current is None:
        raise VibranceError(f"no connected monitor {output}")
    if current["hdr"]:
        raise VibranceError(f"{output} is in HDR mode; vibrance works on SDR screens")
    cfg = config.load()
    saved = config.section(cfg, "vibrance", output)
    if "source" not in saved and level_of(current) == NEUTRAL:     # remember what to go back to
        saved.update(source=current["source"] or "sRGB", icc=current["icc"])
    if level == NEUTRAL:
        back = saved.get("source", "sRGB")
        args = [f"output.{output}.colorProfileSource.{back}"]
        if back == "ICC" and saved.get("icc"):
            args.insert(0, f'output.{output}.iccprofile.{saved["icc"]}')
        _doctor(*args)
        cfg["vibrance"].pop(output, None)
        prune(output)
    else:
        os.makedirs(DIR, exist_ok=True)
        path = os.path.join(DIR, f"rigdeck-vibrance-{output}-{level}.icc")
        with open(path, "wb") as f:
            f.write(profile(level, f"RigDeck vibrance {level}% ({output})"))
        _doctor(f"output.{output}.iccprofile.{path}", f"output.{output}.colorProfileSource.ICC")
        saved["level"] = level
        prune(output, keep=path)
    config.save(cfg)
